name: Lint Codebase
on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: squarebtech/eslint/.github/workflows/eslint.yaml@main
    with:
      node-version: '20'
    secrets:
      access-token: ${{ secrets.SBT_TOKEN }}
