name: Status Check Functions
on: [push]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: sleep 20
      - name: Runs on failure
        if: failure()
        run: echo 'Runs only on failure'
      - name: Runs on success
        # This is the default behavior
        if: success()
        run: echo 'Runs on success'
      - name: Always runs
        if: always()
        run: echo 'Always runs'
      - name: Runs when canceled
        if: cancelled()
        run: echo 'Runs on cancel'
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    if: failure()
    steps:
      - run: echo 'Job 2'
